name = "C"
uuid = "f7183063-27c6-4896-8c1a-08c8019d1b07"
authors = ["lassepe <lasse.peters@mailbox.org>"]
manifest = "../Manifest.toml"
version = "0.1.0"

[deps]
B = "548c7614-e21f-42c6-b6ad-b6135acb27a3"
